services:
  webserver:
    container_name: static-website
    image: lipanski/docker-static-website:latest
    restart: unless-stopped
    networks:
      - traefik-proxy
    volumes:
      - ./static:/home/static
      - ./httpd.conf:/home/static/httpd.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static-site.rule=Host(`10w.nl`)"
      - "traefik.http.routers.static-site.tls.certResolver=cloudflare"
      - "traefik.http.services.static-site.loadbalancer.server.port=3000"
networks:
  traefik-proxy:
    external: true
