services:
  wirebuddy:
    image: giiibates/wirebuddy:latest
    container_name: wirebuddy
    restart: unless-stopped
    network_mode: host
    #networks:
    #  - traefik-proxy 
    #ports: 
    #  - 51820:51820
    #  - 9000:8000
    cap_add:
      - NET_ADMIN       # Required for network configuration
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wgbuddy.rule=Host(`wgbuddy.10w.nl`)"
      - "traefik.http.routers.wgbuddy.entrypoints=websecure"
      - "traefik.http.routers.wgbuddy.service=wgbuddy"
      - "traefik.http.services.wgbuddy.loadbalancer.server.port=8000"

#networks:
#  traefik-proxy:
#    external: true
